
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - services.huebernetes.dev
  resources:
  - lights
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.huebernetes.dev
  resources:
  - lights/finalizers
  verbs:
  - update
- apiGroups:
  - services.huebernetes.dev
  resources:
  - lights/status
  verbs:
  - get
  - patch
  - update
